name: Build executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt update -y
        sudo apt install chrpath

    - name: Build executable
      run: |
        python3 -m nuitka --standalone --plugin-enable=tk-inter YTPMVE.py
        mv ./YTPMVE.dist/YTPMVE ./YTPMVE.dist/YTPMVE.exe
    - uses: actions/upload-artifact@v2
      with:
        name: YTPMVE
        path: ./YTPMVE.dist/YTPMVE.exe